In [1]:
import pandas as pd

In [2]:
first_array=pd.Series([3,2,0,1])
first_array

0    3
1    2
2    0
3    1
dtype: int64

In [3]:
first_array.name="apple"

In [4]:
first_array

0    3
1    2
2    0
3    1
Name: apple, dtype: int64

In [5]:
first_array[1]

np.int64(2)

In [6]:
second_array=pd.Series([3,2,0,1],index=['a','b','c','d'])
second_array

a    3
b    2
c    0
d    1
dtype: int64

In [7]:
second_array['c']

np.int64(0)

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
#2d array  # here 4,5 are start and end range  numbers and also 3,4 is rows indexes
import numpy as np
np.random.randint(4,5,(3,4))

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int32)

In [10]:
np.random.randn(3,4)

array([[-0.96367813,  0.0825034 , -0.90133995, -1.08502286],
       [-0.06760654, -1.56919247,  0.89512132,  1.47452229],
       [-1.66823995,  0.29820437,  0.23155263, -0.46065395]])

In [11]:
#dataframe 
import numpy as np
some_2d_array=np.random.randint(4,5,(3,4))
some_2d_array

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int32)

In [12]:
import pandas as pd
first_dataframe=pd.DataFrame(some_2d_array)
first_dataframe

0  1  2  3
0  4  4  4  4
1  4  4  4  4
2  4  4  4  4

In [13]:
second_dataframe = pd.DataFrame(some_2d_array, columns=['sri','chandra','yash','dhanush'])
second_dataframe

sri  chandra  yash  dhanush
0    4        4     4        4
1    4        4     4        4
2    4        4     4        4

In [14]:
second_dataframe = pd.DataFrame(some_2d_array, columns=['sri','chandra','yash','dhanush'],index=['first','second','third'])
second_dataframe

sri  chandra  yash  dhanush
first     4        4     4        4
second    4        4     4        4
third     4        4     4        4

In [15]:
#using Conventional list of list 

In [16]:
x=[["sri",20],["dhanush",21],["yash",30]]
x

[['sri', 20], ['dhanush', 21], ['yash', 30]]

In [17]:
import pandas as pd
pd.DataFrame(x)

0   1
0      sri  20
1  dhanush  21
2     yash  30

In [18]:
data = pd.DataFrame(x, columns=['Name', 'Age'])
data


Name  Age
0      sri   20
1  dhanush   21
2     yash   30

In [19]:
#List of Disctionary into DataFrame  imp question for interview what are the ways to createdataframe 
list_of_dict = [{"Name":"SRI", "Values": 100},
                {"Name": "YASH", "Values": 200}]
import pandas as pd
df = pd.DataFrame(list_of_dict)
df

Name  Values
0   SRI     100
1  YASH     200

In [20]:
#using a dictionary as a list
a={"Name":["Alice","john"],"marks":[20,40]}
a

{'Name': ['Alice', 'john'], 'marks': [20, 40]}

In [21]:
pd.DataFrame(a)

Name  marks
0  Alice     20
1   john     40

In [22]:
values = [100,200,300,400,500]
name = ['Geeta','Dhanush','Geeta','Gousiya','Jay']
merged_two_list = [values , name]
df = pd.DataFrame(merged_two_list)
#Converting horizontal row format to vertical column format
df_t = df.transpose()
df_t.columns = ['Values', 'Name']
df_t

Values     Name
0    100    Geeta
1    200  Dhanush
2    300    Geeta
3    400  Gousiya
4    500      Jay

In [23]:
#dataframe 
import numpy as np
some_2d_array=np.random.randint(10,40,(100,5))
some_2d_array

array([[19, 24, 25, 27, 29],
       [14, 15, 24, 28, 27],
       [14, 30, 25, 37, 30],
       [24, 27, 25, 30, 39],
       [31, 10, 16, 39, 33],
       [14, 39, 38, 16, 27],
       [12, 39, 34, 36, 11],
       [18, 35, 22, 28, 17],
       [21, 27, 22, 15, 32],
       [17, 22, 12, 35, 34],
       [18, 35, 36, 24, 35],
       [20, 16, 18, 31, 33],
       [12, 16, 16, 25, 34],
       [30, 35, 22, 16, 35],
       [37, 31, 11, 20, 20],
       [34, 34, 25, 10, 25],
       [23, 34, 18, 25, 21],
       [38, 15, 13, 17, 32],
       [36, 34, 35, 33, 14],
       [35, 37, 14, 12, 34],
       [25, 28, 38, 31, 35],
       [17, 13, 14, 34, 23],
       [26, 15, 15, 28, 28],
       [25, 33, 22, 25, 18],
       [14, 12, 28, 33, 10],
       [16, 19, 34, 17, 28],
       [26, 10, 29, 30, 17],
       [16, 29, 30, 38, 36],
       [11, 19, 18, 29, 34],
       [27, 30, 11, 32, 12],
       [29, 18, 26, 19, 30],
       [20, 25, 26, 13, 13],
       [10, 37, 25, 26, 31],
       [21, 35, 33, 25, 22],
       [38, 24

In [24]:
import pandas as pd
Third_dataframe=pd.DataFrame(some_2d_array)
Third_dataframe

0   1   2   3   4
0   19  24  25  27  29
1   14  15  24  28  27
2   14  30  25  37  30
3   24  27  25  30  39
4   31  10  16  39  33
..  ..  ..  ..  ..  ..
95  25  14  36  20  18
96  19  36  37  19  12
97  13  21  26  21  17
98  15  29  25  20  19
99  16  22  26  33  27

[100 rows x 5 columns]

In [25]:
import numpy as np
array=np.random.randint(10,40,(100,5))
df=pd.DataFrame(array,columns=['a','b','c','d','e'])
df

a   b   c   d   e
0   36  14  10  31  19
1   32  27  12  25  25
2   28  25  24  28  36
3   34  36  10  38  17
4   23  35  20  39  30
..  ..  ..  ..  ..  ..
95  29  15  14  21  33
96  27  38  19  10  23
97  21  10  17  16  39
98  22  31  26  22  11
99  16  18  12  13  18

[100 rows x 5 columns]

In [26]:
df.shape

(100, 5)

In [27]:
df.tail()

a   b   c   d   e
95  29  15  14  21  33
96  27  38  19  10  23
97  21  10  17  16  39
98  22  31  26  22  11
99  16  18  12  13  18

In [28]:
df.head()

a   b   c   d   e
0  36  14  10  31  19
1  32  27  12  25  25
2  28  25  24  28  36
3  34  36  10  38  17
4  23  35  20  39  30

In [29]:
#Shape Function for [Rows]
df.shape[1]

5

In [30]:
#Shape Function for [Columns]
df.shape[0]

100

In [31]:
#Size Function
df.size

500

In [32]:
#columns 
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [33]:
#list 
list(df.columns)

['a', 'b', 'c', 'd', 'e']

In [34]:
df.describe()

a           b           c           d           e
count  100.000000  100.000000  100.000000  100.000000  100.000000
mean    22.430000   24.630000   23.950000   24.730000   23.570000
std      8.767773    8.735918    8.669434    8.802955    7.861497
min     10.000000   10.000000   10.000000   10.000000   10.000000
25%     14.000000   17.000000   17.000000   18.000000   16.750000
50%     21.500000   24.500000   22.000000   22.500000   24.000000
75%     29.250000   32.250000   31.250000   32.250000   29.000000
max     39.000000   39.000000   39.000000   39.000000   39.000000

In [35]:
#list data columns
list(data.columns)

['Name', 'Age']

In [36]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       100 non-null    int32
 1   b       100 non-null    int32
 2   c       100 non-null    int32
 3   d       100 non-null    int32
 4   e       100 non-null    int32
dtypes: int32(5)
memory usage: 2.1 KB


In [37]:
#Checking the null values
df.isnull()
df.isnull().sum()

a    0
b    0
c    0
d    0
e    0
dtype: int64

In [38]:
#eliminating all the null values
df.dropna(how = "all", inplace = True) #how = "any"
df

a   b   c   d   e
0   36  14  10  31  19
1   32  27  12  25  25
2   28  25  24  28  36
3   34  36  10  38  17
4   23  35  20  39  30
..  ..  ..  ..  ..  ..
95  29  15  14  21  33
96  27  38  19  10  23
97  21  10  17  16  39
98  22  31  26  22  11
99  16  18  12  13  18

[100 rows x 5 columns]

In [39]:

df.head() #Printing the first 4 rows
df.head(10) #Printing the first 4 rows
df.head(-10) #Print all the rows except the last 8 rows

a   b   c   d   e
0   36  14  10  31  19
1   32  27  12  25  25
2   28  25  24  28  36
3   34  36  10  38  17
4   23  35  20  39  30
..  ..  ..  ..  ..  ..
85  37  38  38  19  25
86  17  25  23  20  20
87  11  23  19  36  36
88  11  11  15  32  16
89  26  30  14  35  29

[90 rows x 5 columns]

In [40]:
# @title Removing rows
#Removing Rows
df.drop([1,2,6],axis = 0) #rows

a   b   c   d   e
0   36  14  10  31  19
3   34  36  10  38  17
4   23  35  20  39  30
5   13  36  24  22  27
7   24  33  15  18  16
..  ..  ..  ..  ..  ..
95  29  15  14  21  33
96  27  38  19  10  23
97  21  10  17  16  39
98  22  31  26  22  11
99  16  18  12  13  18

[97 rows x 5 columns]

In [41]:
print(df.columns.tolist())

['a', 'b', 'c', 'd', 'e']


In [42]:
#removing columns
df = df.drop("b", axis=1)


In [43]:
df

a   c   d   e
0   36  10  31  19
1   32  12  25  25
2   28  24  28  36
3   34  10  38  17
4   23  20  39  30
..  ..  ..  ..  ..
95  29  14  21  33
96  27  19  10  23
97  21  17  16  39
98  22  26  22  11
99  16  12  13  18

[100 rows x 4 columns]

In [44]:
# @title Renaming a Column
df.rename(columns = {"c" : "sri"},inplace = True)
df

a  sri   d   e
0   36   10  31  19
1   32   12  25  25
2   28   24  28  36
3   34   10  38  17
4   23   20  39  30
..  ..  ...  ..  ..
95  29   14  21  33
96  27   19  10  23
97  21   17  16  39
98  22   26  22  11
99  16   12  13  18

[100 rows x 4 columns]

In [45]:
# @title Unique Function
#Finding the Unique values from the given Column
pd.unique(df['a'])

array([36, 32, 28, 34, 23, 13, 21, 24, 17, 12, 37, 14, 10, 39, 16, 35, 18,
       11, 19, 25, 33, 22, 27, 31, 26, 20, 29, 38, 30], dtype=int32)