In [51]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM

In [52]:
x=[]
y=[]

#sequence1=np.arange(10,110,10)
sequence=[]
for i in range(10,110,10):
    sequence.append(i)

sequence

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [53]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
sequence=scaler.fit_transform(np.array(sequence).reshape(-1,1))
sequence

array([[0.        ],
       [0.11111111],
       [0.22222222],
       [0.33333333],
       [0.44444444],
       [0.55555556],
       [0.66666667],
       [0.77777778],
       [0.88888889],
       [1.        ]])

In [54]:
#list(sequence1)

for i in range(len(sequence)-3):
    x.append(sequence[i:i+3]) # 3 time steps
    y.append(sequence[i+3])#next value to predict

In [55]:
x

[array([[0.        ],
        [0.11111111],
        [0.22222222]]),
 array([[0.11111111],
        [0.22222222],
        [0.33333333]]),
 array([[0.22222222],
        [0.33333333],
        [0.44444444]]),
 array([[0.33333333],
        [0.44444444],
        [0.55555556]]),
 array([[0.44444444],
        [0.55555556],
        [0.66666667]]),
 array([[0.55555556],
        [0.66666667],
        [0.77777778]]),
 array([[0.66666667],
        [0.77777778],
        [0.88888889]])]

In [56]:
y

[array([0.33333333]),
 array([0.44444444]),
 array([0.55555556]),
 array([0.66666667]),
 array([0.77777778]),
 array([0.88888889]),
 array([1.])]

In [57]:
x=np.array(x)
y=np.array(y)

In [58]:
x.shape

(7, 3, 1)

In [59]:
x=x.reshape((x.shape[0],x.shape[1],1))

In [60]:
x.shape

(7, 3, 1)

In [61]:
x

array([[[0.        ],
        [0.11111111],
        [0.22222222]],

       [[0.11111111],
        [0.22222222],
        [0.33333333]],

       [[0.22222222],
        [0.33333333],
        [0.44444444]],

       [[0.33333333],
        [0.44444444],
        [0.55555556]],

       [[0.44444444],
        [0.55555556],
        [0.66666667]],

       [[0.55555556],
        [0.66666667],
        [0.77777778]],

       [[0.66666667],
        [0.77777778],
        [0.88888889]]])

In [62]:
#lstm model creation
model=Sequential([
    LSTM(50,activation='tanh',input_shape=(3,1)),
    Dense(1)
])

c:\Users\sasan\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [63]:
# Compile the model
model.compile(optimizer='adam',loss='mse')

In [64]:
model.fit(x,y,epochs=500,verbose=0)

In [67]:
# model prediction ex-1
test_input = np.array([70, 80, 90]).reshape(3,1)
test_input=scaler.transform(test_input)
test_input = test_input.reshape((1, 3, 1))

y_pred = model.predict(test_input)
y_pred=scaler.inverse_transform(y_pred)
print(f"predict next is: {y_pred[0][0]:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
predict next is: 100.72


In [71]:
# model prediction ex-1
test_input = np.array([50,60,70]).reshape(3,1)
test_input=scaler.transform(test_input)
test_input = test_input.reshape((1, 3, 1))

y_pred = model.predict(test_input)
y_pred=scaler.inverse_transform(y_pred)
print(f"predict next is: {y_pred[0][0]:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
predict next is: 79.51
