In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN

In [17]:
x=[]
y=[]

#sequence1=np.arange(10,110,10)
sequence=[]
for i in range(10,110,10):
    sequence.append(i)

sequence

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [18]:
#list(sequence1)

for i in range(len(sequence)-3):
    x.append(sequence[i:i+3]) # 3 time steps
    y.append(sequence[i+3])#next value to predict

In [19]:
x

[[10, 20, 30],
 [20, 30, 40],
 [30, 40, 50],
 [40, 50, 60],
 [50, 60, 70],
 [60, 70, 80],
 [70, 80, 90]]

In [20]:
y

[40, 50, 60, 70, 80, 90, 100]

In [23]:
x=np.array(x)
y=np.array(y)

In [24]:
x

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80],
       [70, 80, 90]])

In [25]:
x.shape

(7, 3)

In [26]:
x=x.reshape((x.shape[0],x.shape[1],1))

In [27]:
x

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]],

       [[70],
        [80],
        [90]]])

In [11]:
# model creation
model=Sequential([
    SimpleRNN(50,activation='relu',input_shape=(3,1)),
    Dense(1)
])

c:\Users\sasan\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [12]:
# Compile the model
model.compile(optimizer='adam',loss='mse')

In [13]:
model.fit(x,y,epochs=300,verbose=1)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 3982.9097
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 3704.5823
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 3436.3547
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 3183.7732
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 2937.2969
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 2691.3386
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 2451.6528
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 2219.6169
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 1996.2893
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1782.8390
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 1580.1276
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 1391.3370
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 1214.6124
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1050.3385
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms

In [14]:
# model prediction ex-1
test_input = np.array([80, 90, 100])
test_input = test_input.reshape((1, 3, 1))

prediction = model.predict(test_input)
print(f"predict next is: {prediction[0][0]:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step
predict next is: 117.75


In [15]:
# ex-2
test_input = np.array([[50, 60, 70]])
test_input = test_input.reshape((1, 3, 1))

prediction = model.predict(test_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[80.26254]], dtype=float32)